# Generated by Django 4.1.6 on 2023-02-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kitchenmodel_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KitchenModel',
            new_name='Kitchen',
        ),
    ]
